// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRO_4KYBpo0eivBCCBeJNtQN405yPD9Ws',
    appId: '1:720824865533:web:429a8e6ded95d1e1b7e494',
    messagingSenderId: '720824865533',
    projectId: 'talent-pool-82df8',
    authDomain: 'talent-pool-82df8.firebaseapp.com',
    storageBucket: 'talent-pool-82df8.appspot.com',
    measurementId: 'G-HKLW2GFZRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgt6bZXl2opC8BU5vN6EXWA_FSJQ5hGfE',
    appId: '1:720824865533:android:4c57372ca04e1fcab7e494',
    messagingSenderId: '720824865533',
    projectId: 'talent-pool-82df8',
    storageBucket: 'talent-pool-82df8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwZkqRsTQtXNejXqEVKCSTu45Ogy_yIs',
    appId: '1:720824865533:ios:548f8dac0fe3f819b7e494',
    messagingSenderId: '720824865533',
    projectId: 'talent-pool-82df8',
    storageBucket: 'talent-pool-82df8.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkwZkqRsTQtXNejXqEVKCSTu45Ogy_yIs',
    appId: '1:720824865533:ios:548f8dac0fe3f819b7e494',
    messagingSenderId: '720824865533',
    projectId: 'talent-pool-82df8',
    storageBucket: 'talent-pool-82df8.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRO_4KYBpo0eivBCCBeJNtQN405yPD9Ws',
    appId: '1:720824865533:web:dfb53027bdaf178db7e494',
    messagingSenderId: '720824865533',
    projectId: 'talent-pool-82df8',
    authDomain: 'talent-pool-82df8.firebaseapp.com',
    storageBucket: 'talent-pool-82df8.appspot.com',
    measurementId: 'G-ENB2NXZ2KS',
  );
}
